language: java
jdk: oraclejdk11
sudo: false

deploy:
  provider: script
#  script: "mvn -B -V deploy"
  script: "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pdev"
#  script: "mvn clean build -Pdev"
  skip_cleanup: true
